### ISSUE TITLE
It would be better to replace `code*` with `codef`

### ISSUE THREAD

**Issue by theJiawen** [alexchantastic/alfred-open-with-vscode-workflow#1]
Thanks for the nice job!

Just a slight suggestion, as the tittle suggest, I think it would be better to use `codef` (means \`code folder\`) than `code*`, as the character `*` is not easy to type.  

It's easy to modify it myself though.

**Comment by alexchantastic** [comment]
I don't really use `code*` too often so I never really noticed the issues with `*` as a character. I think this is a good idea.
