### ISSUE TITLE
Fixed search directory to desktop, and can associate an existed project when type word

### ISSUE THREAD

**Issue by twotwoba** [alexchantastic/alfred-open-with-vscode-workflow#10]
I often put my projects on desktop, so I changed the `${query}` to `~/Desktop/{query}`, but it can't associate the project name with tab, can we achieve this function?

**Comment by alexchantastic** [comment]
Instead of modifying the script, what you'll want to do instead is add a scope restriction to the file filter.

Here are some instructions on how to do this:

1. Open the workflow in the Alfred workflow editor
2. Edit the `codef` node
    <img width="240" alt="image" src="https://user-images.githubusercontent.com/604167/191682472-1130367d-f483-4d4c-92d6-f0d1d2b8aa6c.png">
3. Click the **Scope** tab and drag your desktop folder into the list
     ![image](https://user-images.githubusercontent.com/604167/191682222-2f05b3cc-aa8d-4a51-b0cb-e10085566bfd.png)
4. Click **Save**

Now when you use the `codef` keyword, it will only search for files in `~/Desktop`!

Let me know if this works for you.

**Comment by twotwoba** [comment]
> Instead of modifying the script, what you'll want to do instead is add a scope restriction to the file filter.
> 
> Here are some instructions on how to do this:
> 
> 1. Open the workflow in the Alfred workflow editor
> 2. Edit the `codef` node
>    <img alt="image" width="240" src="https://user-images.githubusercontent.com/604167/191682472-1130367d-f483-4d4c-92d6-f0d1d2b8aa6c.png">
> 3. Click the **Scope** tab and drag your desktop folder into the list
>    ![image](https://user-images.githubusercontent.com/604167/191682222-2f05b3cc-aa8d-4a51-b0cb-e10085566bfd.png)
> 4. Click **Save**
> 
> Now when you use the `codef` keyword, it will only search for files in `~/Desktop`!
> 
> Let me know if this works for you.

Thanks for you reply!

**Comment by twotwoba** [comment]
But, what i want is, if there's a project named 'Good job', and  when I type 'Good' and press 'TAB' then, can it autofill in alfred?

**Comment by alexchantastic** [comment]
I think if you have projects in individual folders, you can also set a File Type filter to only look for folders. To do that, open up the workflow like before and go to the **Basic Setup** tab.

In the **File Types** list, drag in a folder (it can be any folder). The list should then look like this:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/604167/192072072-22e09ca2-1003-4f0a-9a88-139c21f38835.png">

Click **Save** and you should be good to go!

**Comment by twotwoba** [comment]
I'm sorry for that I didn't try it according to your first reply and I do it today. Your first answer has accurately solved my problem. Thank you very much!

**Comment by twotwoba** [comment]
It's really  an excellent plugin!
