### ISSUE TITLE
Show hints while typing a path

### ISSUE THREAD

**Issue by aurexav** [alexchantastic/alfred-open-with-vscode-workflow#13]
If there are some auto-completions, that would be better.

**Comment by alexchantastic** [comment]
Sorry for the late response! Are you not seeing file filters when you use the `codef` keyword?

**Comment by acgxv** [comment]
> Sorry for the late response! Are you not seeing file filters when you use the `codef` keyword?

Yep, that works.

But I want to go a specific path instead of searching.

Typing `/Users/...` or `~/Doocuments/...`.
