### ISSUE TITLE
Restrict codef to path

### ISSUE THREAD

**Issue by DanielOfir** [alexchantastic/alfred-open-with-vscode-workflow#16]
Hi,

Is it possible to restrict `codef` results to a specific directory and subdirectories? i.e. under the path `/Users/user/Documents/Projects`, there are multiple directories containing different projects.
When typing `codef` it should only pull up results under the specified path.

Thanks

**Comment by alexchantastic** [comment]
Hi @DanielOfir,

Alfred provides a way to limit the search scope of a file filter which is what `codef` does. You'll need to modify the workflow a tiny bit, but that should get you where you want to be.

Here's a comment in an older issue I wrote up for a separate issue that goes into how to do just that: https://github.com/alexchantastic/alfred-open-with-vscode-workflow/issues/10#issuecomment-1254625822

**Comment by DanielOfir** [comment]
@alexchantastic that works great, thanks for that!
