### ISSUE TITLE
Monterey 12.3 - "The application “Visual Studio Code.app” can’t be opened." dialog

### ISSUE THREAD

**Issue by danstreeter** [alexchantastic/alfred-open-with-vscode-workflow#8]
After upgradng to Monterey 12.3, the workflow stopped working and showed a finder dialog error and nothing else happened. (was on Workflow v1.0.0 at the time)

Upon upgrading to the latest (v1.1.1) I still get the dialog, but VSCode now opens as expected.

![image](https://user-images.githubusercontent.com/20464844/158460586-df35944a-4c41-476e-b84e-08483148cfeb.png)

**Comment by danstreeter** [comment]
Some further debug - I cannot open two VSCode instances from differing directories using this method... only the first works until I close it.

**Comment by shunichio** [comment]
I have the same problem.

**Comment by viktorbijlenga** [comment]
I have similiar issue with another VS Code Workflow for Alfred by @franzheidl
https://github.com/franzheidl/alfred-workflows/issues/23

**Comment by alexchantastic** [comment]
Thanks for reporting this! I was able to reproduce it after upgrading to macOS Monterey 12.3. This does seem to be a widespread issue with the 12.3 update: https://developer.apple.com/forums/thread/702315

I've released a fix under [v1.2.0](https://github.com/alexchantastic/alfred-open-with-vscode-workflow/releases/tag/v1.2.0). Let me know if that works for you and I'll close this issue out.

**Comment by danstreeter** [comment]
I can confirm that `1.2.0` fixes the problem, thanks for the rapid resolution!
